### ISSUE TITLE
Problems opening books - specifically 1984-06-computegazette

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#370]
@vlnn in issue #365 - the specific bug - a bug in the server that responds to Archive's BookReaderJSIA is worked around, but there are other bugs that stop this page opening... Will leave this open as a meta-bug and open specific separate bugs as I work through getting books to work again. 

Note ... this is now a volunteer thing for me, so it may take time - feel free to jump in and help.

**Comment by mitra42** [comment]
Bug #369 occurs at startup of dweb-mirror

**Comment by vlnn** [comment]
@mitra42 Understood -- thanks for the investigation and support. Alas JS is not in my stack, so perhaps my help here would be more of burden. Still, if anything related to QA/documentation or really simple fixes will come around, please let me know.

**Comment by mitra42** [comment]
Fixed bug #369, but hit a new one with the images bug #371 - next one to tackle. ....

**Comment by mitra42** [comment]
This is fixed now - dweb-mirror v0.2.92 sucessfully opens your test case i.e. `/details/1984-06-computegazette`
@vlnn  please feel free to open new issues if you find other things that fail - though can't promise speedy fixes. 

With the volunteer time I have available,  I'm working through about one significant bug every week or two.

**Comment by vlnn** [comment]
Yes! It totally works now, thank you @mitra42 (sorry, it took some extra time to check due to blackouts here in Kyiv). I also see that some minor issues with icons and small images on the page are also resolved now. Super cool!
<img width="845" alt="CleanShot 2022-12-24 at 16 59 27@2x" src="https://user-images.githubusercontent.com/29273499/209441673-5e43e163-5a09-4ff9-825d-7464c0b74c6c.png">

**Comment by holta** [comment]
Heroic work.

Profound thanks @mitra42 and @vlnn :christmas_tree:
